# Generated by Django 3.2.5 on 2021-07-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Doggers', '0004_mascota_idusuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agenda',
            old_name='idUsuarios',
            new_name='idUsuario',
        ),
        migrations.RenameField(
            model_name='mascota',
            old_name='idUsuarios',
            new_name='idUsuario',
        ),
    ]
