/* eslint-disable import/no-anonymous-default-export */
export const CREAR_PASEADOR = "CREAR_PASEADOR";
export const AGREGAR_PASEADOR_ERROR = "AGREGAR_PASEADOR_ERROR";
export const CREAR_USUARIO = "CREAR_USUARIO";
export const AGREGAR_USUARIO_ERROR = "AGREGAR_USUARIO_ERROR";
export const OBTENER_USUARIO = "OBTENER_USUARIO";
export const AGREGAR_MASCOTA_ERROR = "AGREGAR_MASCOTA_ERROR";
export const CREAR_MASCOTA = "CREAR_MASCOTA";
export const CREAR_AGENDA = "CREAR_AGENDA";
export const OBTENER_AGENDA = "OBTENER_AGENDA";
export const AGREGAR_AGENDA_ERROR = "AGREGAR_AGENDA_ERROR"
//ALERTAS
export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";